# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 05:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('registration_tag', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('total_sits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarDocument',
            fields=[
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Cars.Car')),
                ('insurance_policy', models.ImageField(upload_to=b'static/uploads/documents/')),
                ('circulation_car', models.ImageField(upload_to=b'static/uploads/documents/')),
                ('licence', models.ImageField(upload_to=b'static/uploads/documents/')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
