# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardocument',
            old_name='circulation_car',
            new_name='circulation_card',
        ),
    ]
