# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 22:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0004_auto_20170108_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('university_pk', models.IntegerField(default=0)),
                ('car_pk', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=75)),
                ('origin', models.CharField(max_length=75)),
                ('sits', models.IntegerField(default=0)),
                ('start_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteDay',
            fields=[
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Routes.Route')),
                ('day', models.CharField(default=b'', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='RouteMarker',
            fields=[
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Routes.Route')),
                ('position', models.IntegerField(default=0)),
                ('latitude', models.CharField(default=b'', max_length=150)),
                ('longitude', models.CharField(default=b'', max_length=150)),
            ],
        ),
    ]
