# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 01:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_pk', models.IntegerField(default=0)),
                ('car_pk', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=75)),
                ('origin', models.CharField(max_length=75)),
                ('sits', models.IntegerField(default=0)),
                ('start_time', models.TimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RouteDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default=b'', max_length=75)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Routes.Route')),
            ],
        ),
        migrations.CreateModel(
            name='RouteMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('latitude', models.CharField(default=b'', max_length=150)),
                ('longitude', models.CharField(default=b'', max_length=150)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Routes.Route')),
            ],
        ),
    ]
