# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-20 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='university_pk',
            new_name='campus_pk',
        ),
    ]
