# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
