# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0002_auto_20170406_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='create_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
