# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
                ('latitude', models.CharField(default=b'0', max_length=150)),
                ('longitude', models.CharField(default=b'0', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Studies.University')),
                ('name', models.CharField(default=b'0', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('campus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Studies.Campus')),
                ('name', models.CharField(default=b'0', max_length=150)),
            ],
        ),
    ]
