# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='university',
            name='longitude',
        ),
        migrations.AddField(
            model_name='campus',
            name='latitude',
            field=models.CharField(default=b'0', max_length=150),
        ),
        migrations.AddField(
            model_name='campus',
            name='longitude',
            field=models.CharField(default=b'0', max_length=150),
        ),
    ]
