# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-08 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.IntegerField(null=True),
        ),
    ]
