# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_user_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_admin_type',
            field=models.IntegerField(choices=[(0, 'Superadmin'), (1, 'Universidad'), (2, 'Facultad'), (3, 'Usuario')], default=3),
        ),
    ]
