# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20170414_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
